#!/bin/bash

TESTS="\
  examples/peter/Append.core\
  examples/peter/Factorial.core\
  examples/peter/Raytracer.core\
  examples/peter/SumTree.core\
  examples/peter/TreeFlip.core\
  examples/imaginary/Bernouilli.core\
  examples/imaginary/DigitsOfE2.core\
  examples/imaginary/Exp3_8.core\
  examples/imaginary/Primes.core\
  examples/imaginary/RFib.core\
  examples/imaginary/Tak.core\
  examples/imaginary/X2N1.core\
  "
  # Disabling this for now as it's broken.
  # TODO(osa1): Figure out why it's broken.
  # examples/neil/SumSquare.core\

# Supercompiling examples/imaginary/Wheel-Sieve*.core takes too long

./test $* $TESTS || exit $?
